name: base
channels:
  - conda-forge
dependencies:
  - python = 3.8

  - plotly = 5.9.0
  - watchdog = 2.1.6

  - gsw = 3.6.16
  - pyarrow = 12.0.0

  - pip = 23.1.2
  - pip:
      - git+https://github.com/euroargodev/argopy
